### ISSUE TITLE
Dockerfile clone master repo

### ISSUE THREAD

**Issue by yawboateng** [bitsensor/elastalert#1]
Readme states Yelp's ElastAlert v0.0.96 as the version you support, yet I notice the [ Dockerfile](https://github.com/bitsensor/elastalert/blob/master/Dockerfile) clones the master repo. 

`RUN git clone https://github.com/Yelp/elastalert.git -b master --depth=1 /opt/elastalert`

is there a reason for that, if you only support v0.0.96, why not use the [release](https://github.com/Yelp/elastalert/releases/tag/v0.0.96)?

**Comment by RubieV** [comment]
To merge in hotfixes and patches. If ElastAlert breaks, you can just
fallback to the 0.0.96 release.

Op zo 26 mrt. 2017 23:25 schreef yawboateng <notifications@github.com>:

**Comment by yawboateng** [comment]
ok, cool. thnx
