### ISSUE TITLE
How to create docker image in windows system

### ISSUE THREAD

**Issue by Kuldeep6290** [bitsensor/elastalert#111]
Please can any one help in installing elastalert server in windows system.
I am new to docker and other concepts. I hav installed plugin in KIBANA but unable to install server using docker.

**Comment by kuldeeppatil6290** [comment]
Issue is resolved below command needs to be executed to create image using Powershell in windows
docker run -p 3030:3030 -p 3333:3333 --name elastalert -v ${PWD}\config\elastalert.yaml://opt/elastalert/config.yaml -v ${PWD}\config\elastalert-test.yaml://opt/elastalert/config-test.yaml -v ${PWD}\config\config.json://opt/elastalert-server/config/config.json -v ${PWD}\rules://opt/elastalert/rules -v ${PWD}\rule_templates://opt/elastalert/rule_templates --net="host"  bitsensor/elastalert:3.0.0-beta.0
