### ISSUE TITLE
The docker machine is not working

### ISSUE THREAD

**Issue by tbhaxor** [bitsensor/elastalert#171]
After running the docker command in readme, the container runs for few seconds and then stopped.

![image](https://user-images.githubusercontent.com/28386721/79939694-66481580-847d-11ea-8529-56cd4260f375.png)

**Comment by nsano-rururu** [comment]
@tbhaxor 

As you can imagine, with the Elasticsearch Docker container not started,
I suspect that I ran the docker run command using the Docker image of bitsensor/elastalert:latest and tried to connect to Elasticsearch , but failed and failed many times.


Below is additional information

The Docker image of bitsensor/elastalert:latest is the same as bitsensor/elastalert:2.0.1.
Not compatible with Elasticsearch 7.x (ElastAlert v0.1.39)
Elasticsearch 7.x is compatible with bitsensor/elastalert:3.0.0-beta.0. (ElastAlert v0.2.0b2 is included)

bitsensor/elastalert:latest、bitsensor/elastalert:2.0.1  Dockerfile
https://github.com/bitsensor/elastalert/blob/2.0.1/Dockerfile

bitsensor/elastalert:3.0.0-beta.0  Dockerfile
https://github.com/bitsensor/elastalert/blob/3.0.0-beta.0/Dockerfile
