### ISSUE TITLE
How do you make a rule that sends an alert when mount (e.g. "/software" ) does not exist on one of the nodes

### ISSUE THREAD

**Issue by talcoh2x** [bitsensor/elastalert#179]
I collect my data with metricbeat

'''
system.filesystem.mount_point : /software
'''

**Comment by nsano-rururu** [comment]
This project is dead. I don't think anyone will answer

**Comment by nsano-rururu** [comment]
No one answers. Search for past issues.

**Comment by nsano-rururu** [comment]
bitsensor/elastalert is no longer maintained.
