### ISSUE TITLE
Catch Scroll Clear NotFound Error

### ISSUE THREAD

**Issue by bylankai** [bitsensor/elastalert#183]
Hey I'm facing the same issue as described here https://github.com/Yelp/elastalert/pull/2394
and then realized the latest release here was last May so that update is not included yet. 

I'm wondering when is the next release. Any ideas?

**Comment by nsano-rururu** [comment]
@bylankai 

It's best to assume that it's not a new release.

https://github.com/bitsensor/elastalert/pull/157#issuecomment-651797444
>Hi all,
I emailed one of the project's contributors and he said that bitsensor the company went under, and revoked maintainer rights on this repo.
>
>So, the best way forward is probably to fork and maintain it all together. What do you say?
>Let's pool our resources and work on a single fork.

Please refer to the following issue and decide for yourself whether to create a Docker image based on the latest ElastAlert 0.2.4 or to select a Docker image that is still maintained.

[Release 3.0.0 #156](https://github.com/bitsensor/elastalert/issues/156)

Docker images

| Docker image name    | tag| ElastAlert |Elasticsearch 7 Support|   Remarks    |
|:-------------------|:----:|:----------:|:----------:|:-----------|
|[daichi703n/elastalert](https://hub.docker.com/r/daichi703n/elastalert)|0.2.1-dev2|0.2.1|〇|servercentral/elastalert fork<br>Customize<br>bugfix|
|[praecoapp/elastalert-server](https://hub.docker.com/r/praecoapp/elastalert-server)|latest|0.2.4|〇|servercentral/elastalert fork<br>Customize<br>bug fix<br>Library Update<br>Python 3.8|

**Comment by bylankai** [comment]
@nsano-rururu , 

Thanks for the information. And sure let me try those docker images.

Thanks,
CK
