### ISSUE TITLE
Error while starting Elastalert

### ISSUE THREAD

**Issue by ShiLongTowngrass** [bitsensor/elastalert#185]
I've already used 3.0.0 why is this still an error?

> @bitsensor/elastalert@3.0.0-beta.0 start /root/elastalert-server
> sh ./scripts/start.sh

05:47:50.421Z  INFO elastalert-server: Config:  No config.dev.json file was found in /root/elastalert-server/config/config.dev.json.
05:47:50.422Z  INFO elastalert-server: Config:  Proceeding to look for normal config file.
05:47:50.423Z  INFO elastalert-server: Config:  A config file was found in /root/elastalert-server/config/config.json. Using that config.
05:47:50.430Z  INFO elastalert-server: Router:  Listening for GET request on /.
05:47:50.430Z  INFO elastalert-server: Router:  Listening for GET request on /status.
05:47:50.431Z  INFO elastalert-server: Router:  Listening for GET request on /status/control/:action.
05:47:50.431Z  INFO elastalert-server: Router:  Listening for GET request on /status/errors.
05:47:50.431Z  INFO elastalert-server: Router:  Listening for GET request on /rules.
05:47:50.433Z  INFO elastalert-server: Router:  Listening for GET request on /rules/:id.
05:47:50.433Z  INFO elastalert-server: Router:  Listening for POST request on /rules/:id.
05:47:50.433Z  INFO elastalert-server: Router:  Listening for DELETE request on /rules/:id.
05:47:50.433Z  INFO elastalert-server: Router:  Listening for GET request on /templates.
05:47:50.433Z  INFO elastalert-server: Router:  Listening for GET request on /templates/:id.
05:47:50.433Z  INFO elastalert-server: Router:  Listening for POST request on /templates/:id.
05:47:50.433Z  INFO elastalert-server: Router:  Listening for DELETE request on /templates/:id.
05:47:50.433Z  INFO elastalert-server: Router:  Listening for POST request on /test.
05:47:50.434Z  INFO elastalert-server: Router:  Listening for GET request on /config.
05:47:50.434Z  INFO elastalert-server: Router:  Listening for POST request on /config.
05:47:50.434Z  INFO elastalert-server: Router:  Listening for POST request on /download.
05:47:50.434Z  INFO elastalert-server: Router:  Listening for GET request on /metadata/:type.
05:47:50.434Z  INFO elastalert-server: Router:  Listening for GET request on /mapping/:index.
05:47:50.434Z  INFO elastalert-server: Router:  Listening for POST request on /search/:index.
05:47:50.438Z  INFO elastalert-server: ProcessController:  Starting ElastAlert
05:47:50.438Z  INFO elastalert-server: ProcessController:  Creating index
05:47:50.457Z ERROR elastalert-server:
    ProcessController:  /bin/python: No module named elastalert
    
05:47:50.457Z ERROR elastalert-server: ProcessController:  Index create exited with code 1
05:47:50.457Z  WARN elastalert-server: ProcessController:  ElastAlert will start but might not be able to save its data!
05:47:50.458Z  INFO elastalert-server: ProcessController:  Starting elastalert with arguments [none]
05:47:50.463Z  INFO elastalert-server: ProcessController:  Started Elastalert (PID: 11012)
05:47:50.464Z  INFO elastalert-server: Server:  Server listening on port 3030
05:47:50.465Z  INFO elastalert-server: Server:  Websocket listening on port 3333
05:47:50.466Z  INFO elastalert-server: Server:  Server started
05:47:50.473Z ERROR elastalert-server:
    ProcessController:  /bin/python: No module named elastalert
    
05:47:50.476Z ERROR elastalert-server: ProcessController:  ElastAlert exited with code 1
05:47:50.476Z  INFO elastalert-server: Server:  Stopping server
05:47:50.476Z  INFO elastalert-server: ProcessController:  ElastAlert is not running
05:47:50.477Z  INFO elastalert-server: Server:  Server stopped. Bye!

**Comment by nsano-rururu** [comment]
ElastAlert Server development is probably over. Imagine there is no support. Probably no new version will come out.

**Comment by nsano-rururu** [comment]
You should consider the Docker image provided by another person.

jertel/elastalert-docker
https://hub.docker.com/r/jertel/elastalert-docker

**Comment by ShiLongTowngrass** [comment]
@nsano-rururu
Hi,sir.
In one case, npm start started with the elastalertPath directory removed, but was warned that data would not be saved.
For example: "elastalertPath":"/root/elastalert",
                     rm -rf /root/elastalert
npm start
02:00:21.782Z  INFO elastalert-server: ProcessController:  Starting ElastAlert
02:00:21.782Z  INFO elastalert-server: ProcessController:  Creating index
02:00:21.789Z ERROR elastalert-server: ProcessController:  Index create exited with code null
02:00:21.789Z  WARN elastalert-server: ProcessController:  ElastAlert will start but might not be able to save its data!
02:00:21.790Z  INFO elastalert-server: ProcessController:  Starting elastalert with arguments [none]
02:00:21.795Z  INFO elastalert-server: ProcessController:  Started Elastalert (PID: undefined)
02:00:21.797Z  INFO elastalert-server: Server:  Server listening on port 3030
02:00:21.797Z  INFO elastalert-server: Server:  Websocket listening on port 3333
02:00:21.798Z  INFO elastalert-server: Server:  Server started
02:00:21.799Z ERROR elastalert-server: ProcessController:  ElastAlert error: Error: spawn python ENOENT
02:00:28.273Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/rules'.

**Comment by nsano-rururu** [comment]
If you want to investigate, please send me the configuration file and environment information. I'm not Esper!

**Comment by nsano-rururu** [comment]
I've only confirmed the operation with docker, so support for direct installation is impossible

**Comment by nsano-rururu** [comment]
Development is over so you should spend your time looking for another tool

**Comment by nsano-rururu** [comment]
Is Elasticsearch described in the configuration file ready to start and connect? Isn't it because it hasn't started in the first place?

**Comment by nsano-rururu** [comment]
ping

**Comment by nsano-rururu** [comment]
Did you give up the solution?

**Comment by nsano-rururu** [comment]
>02:00:21.789Z WARN elastalert-server: ProcessController: ElastAlert will start but might not be able to save its data!

The following Elasticsearch connection settings may be incorrect.
You need to check if Elasticsearch is started and the connection information is correct.

elastalert.yaml

```
# Note that every rule can have its own elasticsearch host
es_host: elasticsearch

# The elasticsearch port
es_port: 9200
```

config.json

```
  "es_host": "elasticsearch",
  "es_port": 9200,
```

**Comment by ShiLongTowngrass** [comment]
sorry,I have been very busy these days and have no shutdown problem. I plan to run it directly in docker mode.
