### ISSUE TITLE
Changing elastalert timestamp(UTC) timezone to localtime(IST)

### ISSUE THREAD

**Issue by Singh-Shivani** [bitsensor/elastalert#204]
Hi,
I want to change my `timestamp `field value(UTC) to IST timezone while sending emails. On kibana it is using localtime(IST) zone but elastalert is using UTC while sending mails.

My current config for `elastalert `- 
![image](https://user-images.githubusercontent.com/47295558/144803199-69b8d6d3-c072-4914-a233-cef7c26f5d02.png)

On emails I'm getting -
![image](https://user-images.githubusercontent.com/47295558/144803298-e84e0a8e-0b4c-42a1-a393-0bedf3cb142f.png)
``

**Comment by nsano-rururu** [comment]
Neither elastalert nor elastalert-server is maintained.

**Comment by nsano-rururu** [comment]
If you need help, ask in the elastalert2 repository.
https://github.com/jertel/elastalert2/discussions

**Comment by Singh-Shivani** [comment]
Thank you for replying @nsano-rururu , I got the **solution**.
here posting the solution for others - 

In rule file's directory - create 2 more files, the hierarchy **must be**
```
your_rule_file.yaml
__init__.py
time_enhancement.py
```
**time_enhancement.py -**
```
from elastalert.enhancements import BaseEnhancement

class TimeEnhancement(BaseEnhancement):
    def process(self, match):
        for k, v in match.items():
            if isinstance(v, str) and v.endswith('Z'):
                try:
                    match[k] = pretty_ts(v)
                except:
                    pass
```
Add these lines  in
**your_rule_file.yaml -** 
```
match_enhancements:
- "time_enhancement.TimeEnhancement"

```

**Comment by nsano-rururu** [comment]
If you want to continue using elastalert-server, I think the following elastalert2-server is good. Because it uses elastalert2
https://github.com/Karql/elastalert2-server
