### ISSUE TITLE
Limit a decimal value to only 2/3 places in elastalert (emails)

### ISSUE THREAD

**Issue by Singh-Shivani** [bitsensor/elastalert#205]
Hi everyone,
How can I **Limit a decimal value** to only 2 decimal places in elastalert??

My config for `rules.yaml `-
```
alert_subject: "Anomaly Alerts: ErrorPercentage {0} against threshold {1}"
alert_subject_args:
- "ErrorPercentage"
- "Upper_Threshold"

```
In emails I get -
**ErrorPercentage - 0.44499381953028205** 
In emails I want -
**ErrorPercentage- 0.44**

**Comment by nsano-rururu** [comment]
If you need help, ask in the elastalert2 repository. 
https://github.com/jertel/elastalert2/discussions

**Comment by Singh-Shivani** [comment]
okay thank you!
