### ISSUE TITLE
Will you add functionality to post non-yaml config files?

### ISSUE THREAD

**Issue by Jimhox** [bitsensor/elastalert#22]
From elastalert docs
import: If specified includes all the settings from this yaml file. This allows common config options to be shared. **Note that imported files that aren’t complete rules should not have a .yml or .yaml suffix so that ElastAlert doesn’t treat them as rules**

**Comment by johnsusek** [comment]
FYI if you are using javascript you can build your rules as a javascript object:

```
let rules = {
  "es_host": "",
  "es_port": 0,
  "index": "",
  "type": "any",
  "name": "",
  "alert": [],
  "filter": [
    {
      "query": {
        "query_string": {
          "query": ""
        }
      }
    }
  ]
}
```

then, convert it to a yaml string using js-yaml package:

```
let yamlString = yaml.safeDump(rules)
```

you can then use this yaml string to POST a rule:

```
axios.post(`/api/rules/ruleName`, { yaml: yamlString })
```

**Comment by martijnrondeel** [comment]
We won't be implementing this but PRs regarding this feature are welcome.
