### ISSUE TITLE
krizsan/elastalert-docker is no longer maintained

### ISSUE THREAD

**Issue by Renol7** [bitsensor/elastalert#28]
ivankrizsan/elastalert docker image **is no longer maintained**, is it a problem? 

Because bitsensor/elastalert repository has a dependency in its docker image creation with it...

**Comment by RubieV** [comment]
The dependency is on the Elastalert build, which is now 5 months old. Feel free to PR.

**Comment by deric** [comment]
This was already solved in #18 but somehow the commit got lost in merges, should I rebase #26?

**Comment by martijnrondeel** [comment]
@deric That would be great, thank you.

**Comment by deric** [comment]
@martijnrondeel Updated. The `Dockerfile` uses multi-stage build that produces smaller runtime images. It requires at least Docker 17.05 for building (you can run the image even on older versions of Docker).

**Comment by Renol7** [comment]
Nice! Thank you @deric

**Comment by martijnrondeel** [comment]
Fixed in https://github.com/bitsensor/elastalert/commit/d968b9cf102723455aa056f84d7fa1618f47bc11 (thanks @deric!)
