### ISSUE TITLE
The container takes hours to get activated

### ISSUE THREAD

**Issue by utsav2307** [bitsensor/elastalert#29]
I deployed the container according to the instructions given. In the beginning it was showing as 0 hits even though i could see the logs in kibana for the same query. So I left it there, but then after 3 hours it automatically started working. What could be the issue here?

My config.yaml file is like this:
es_host: xxx
es_port: 9200
rules_folder: rules
run_every:
  seconds: 30
buffer_time:
  minutes: 1
writeback_index: elastalert_status
alert_time_limit:
  days: 1

The rule file is like this:
name: xxxxxx
type: any
index: xxx*
doc_type: doc
realert:
  seconds: 0
filter:
- query:
    query_string:
      query: "violation.msg:xxxx"
query_key:
 - "requestHeaders.host"
 - "violation.msg"
 - "violation.id"
alert:
  - slack
slack_webhook_url: "xxxxx"
slack_username_override: "xxxxxx"
slack_channel_override: "#xxxx"
slack_emoji_override: ":no_entry_sign:"

slack_msg_color: "danger"
slack_username_override: "ModSecurity"

alert_subject: "Potential malicious requests"

alert_text: "Host: '{0}'\nPath: '{1}'\nRule: '{2}'\nID: '{3}'"
alert_text_type: alert_text_only
alert_text_args: ["requestHeaders.host", "requestedUrl", "violation.msg", "violation.id"]

**Comment by utsav2307** [comment]
So what according to you should be the config file like to get alerts by a maximum delay of 15 sec?

**Comment by RubieV** [comment]
Could you elaborate why exactly you want to get alerts in 15 seconds?

**Comment by utsav2307** [comment]
We wanted to see the errors without delay for better debugging and testing, until we have sorted all the rules and alerts on the elasticsearch index.

Anyways i tried a few combinations, its working now at least for time being.

**Comment by RubieV** [comment]
I would advise you to use the rule test feature for that. It will be faster if you configure it differently, ie buffer_time, and will throw immediately if your configuration is not correct.
