### ISSUE TITLE
Two ElastAlert instances are started

### ISSUE THREAD

**Issue by dm-rfraser** [bitsensor/elastalert#3]
https://github.com/bitsensor/elastalert/blob/master/src/elastalert_server.js#L62  
https://github.com/bitsensor/elastalert/blob/master/src/elastalert_server.js#L68

This spawns a second copy of elastalert that seems to do nothing but send duplicate alerts occasionally and double up everything in the logs.  Was this intended?

**Comment by dm-rfraser** [comment]
If it was intended, it looks like the reference is never saved, so it is not stopped in the stop() method.

**Comment by RubieV** [comment]
Please remove the duplicate lines, test the expected behavior and do a PR.  





On Mon, May 8, 2017 11:14 PM, dm-rfraser notifications@github.com  wrote:
If it was intended, it looks like the reference is never saved, so it is not
stopped in the stop() method.
