### ISSUE TITLE
Does Docker installation has ServiceNowAlerter?

### ISSUE THREAD

**Issue by mukeshchouhan** [bitsensor/elastalert#37]
I am looking to send alerts on service now. 
Does Docker installation has elasealert with service now alerter feature?

Looks like latest version of elastalert has this feature-
https://github.com/Yelp/elastalert

Also, Please let me know which version of elasalert does docker installation uses?

**Comment by martijnrondeel** [comment]
The [latest release (0.0.13)](https://github.com/bitsensor/elastalert/releases/tag/0.0.13) uses the latest ElastAlert version (v0.1.36).
