### ISSUE TITLE
Docker build is broken

### ISSUE THREAD

**Issue by k2patel** [bitsensor/elastalert#38]
Tried against following

make build v=v0.1.31
make build v=v0.1.32
make build v=v0.1.33

All fails with following error.

npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-07-23T18_25_42_505Z-debug.log

**Comment by martijnrondeel** [comment]
What is your npm and node version? Could you also share the complete log:

```
npm ERR! A complete log of this run can be found in:
npm ERR! /root/.npm/_logs/2018-07-23T18_25_42_505Z-debug.log
```

**Comment by k2patel** [comment]
@martijnrondeel : i lost the log .. but will try to reproduce and provide complete log.
Thank you.

**Comment by k2patel** [comment]
Sorry for delay got caught up in routine.
[debug.log](https://github.com/bitsensor/elastalert/files/2306373/debug.log)


Here is the warning from terminal and attached is the log file you requested.

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 2974 packages in 2.317s
found 2 vulnerabilities (1 low, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by martijnrondeel** [comment]
I looked through the log but couldn't find anything. As the log says though I think this is an error with NPM itself and from searching online it might have to do with a corrupt cache. 

I'll close this issue, but, if you have the same issue on other computers please reopen this and let us know.
