### ISSUE TITLE
make build fails

### ISSUE THREAD

**Issue by macedemo** [bitsensor/elastalert#40]
I clones and did a make build and got the error below. 

output from a make build
---------
added 290 packages from 248 contributors and audited 2974 packages in 21.484s
found 2 vulnerabilities (1 low, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
Removing intermediate container a28e125de71d
 ---> 051ce3f32702
Step 22/27 : COPY config/elastalert.yaml /opt/elastalert/config.yaml
 ---> 68bbe1f198b8
Step 23/27 : COPY config/config.json config/config.json
 ---> b6ec44bc55ef
Step 24/27 : COPY rule_templates/ /opt/elastalert/rule_templates
failed to export image: failed to create image: failed to get layer sha256:11973eff44b0dd1124ea6e15ec3b97749b93e20708eda85968fc270ce2c90983: layer does not exist
make: *** [build] Error 1
[moby@localhost elastalert]$ make build

**Comment by macedemo** [comment]
found the answer: https://github.com/moby/moby/issues/36573

**Comment by surfer190** [comment]
@macedemo What did you do?

**Comment by surfer190** [comment]
Ah, you just ran it again...according to that other post
