### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by MonaxGT** [bitsensor/elastalert#45]
Hi!
Can you make new docker release for v0.1.36  Elastalert version?

**Comment by martijnrondeel** [comment]
There's currently a bug with upstream ElastAlert that's causing ElastAlert to crash in the Docker image (https://github.com/Yelp/elastalert/issues/1912). When that's resolved I'll release v0.1.36 to master.

**Comment by martijnrondeel** [comment]
Nevermind, upstream didn't have to do with the missing dependency. It's fixed in d16e5d5cadde9e8e17a52151ac544dd9730ab763.

I'll merge develop to master and release a new version today.

**Comment by martijnrondeel** [comment]
This issue has been fixed in the [latest release (0.0.13)](https://github.com/bitsensor/elastalert/releases/tag/0.0.13).
