### ISSUE TITLE
Cannot build a container

### ISSUE THREAD

**Issue by srolskyi** [bitsensor/elastalert#47]
Hello there, 

I try to build container from your instruction:
I clone a fresh repo, and inside  try to use the command: 
`make build`
and got an error:
```
Sending build context to Docker daemon 145.9 kB
Step 1/26 : FROM alpine:latest as py-ea
Error parsing reference: "alpine:latest as py-ea" is not a valid repository/tag: invalid reference format
make: *** [build] Error 1
```

If I try:
`docker build --build-arg ELASTALERT_URL=https://github.com/Yelp/elastalert/archive/master.zip -t elastalert .`
I got the same error:
```
Sending build context to Docker daemon 145.9 kB
Step 1/26 : FROM alpine:latest as py-ea
Error parsing reference: "alpine:latest as py-ea" is not a valid repository/tag: invalid reference format
```
Where I am wrong?

**Comment by martijnrondeel** [comment]
What is your docker version? (`docker -v`)

**Comment by srolskyi** [comment]
@martijnrondeel 
Docker version 1.13.1, build dded712/1.13.1

**Comment by martijnrondeel** [comment]
It looks like your Docker is outdated. The Dockerfile uses a multi-stage build process which is only available from Docker 17.05 so you will have to update your Docker version to at least 17.05.

**Comment by srolskyi** [comment]
Yeah, after update version docker, build works!

**Comment by martijnrondeel** [comment]
:+1:
