### ISSUE TITLE
 IOError: [Errno 2] No such file or directory: 'config.yaml'

### ISSUE THREAD

**Issue by anilkumar-143** [bitsensor/elastalert#48]
Hi , 
i have installed latest release of Elastalert & kibana 6.4.1 along with kibana elastalert plugin & elasticsearch 6.4.1, and Created a config.yaml file and saved in directory of Elastalert. 
while Running elastalert server it is throwing below error 
`   IOError: [Errno 2] No such file or directory: 'config.yaml'`.
Desperately in need of help :(

**Comment by martijnrondeel** [comment]
Something went wrong with the latest release, I'm working on a fix right now. Sorry for the inconvenience.

**Comment by martijnrondeel** [comment]
I've pushed a new release, [0.0.14](https://github.com/bitsensor/elastalert/releases/tag/0.0.14). Please try that version and let me know if your problems are resolved.

**Comment by martijnrondeel** [comment]
Renaming `config.yaml` to `elastalert.yaml` should solve the issue.

**Comment by anilkumar-143** [comment]
But,in which path can we find this config.yaml , so that we can replace it with elastalert.yaml?

**Comment by martijnrondeel** [comment]
Please check the [installation steps](https://github.com/bitsensor/elastalert#installation), it mentions cloning the repo and the location of the configuration files.
