### ISSUE TITLE
Docker build fails when installing requirements.

### ISSUE THREAD

**Issue by lleontop** [bitsensor/elastalert#5]
There is a failure when building the docker image when installing the requirements.
In more detail when running:

> Step 8/14 : RUN pip install -r requirements.txt
> ....
> Running setup.py install for functools32
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/usr/local/lib/python2.7/dist-packages/setuptools/__init__.py", line 12, in <module>
>         import setuptools.version
>       File "/usr/local/lib/python2.7/dist-packages/setuptools/version.py", line 1, in <module>
>         import pkg_resources
>       File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 70, in <module>
>         import packaging.version
>     ImportError: No module named packaging.version
>     Complete output from command /usr/bin/python -c "import setuptools, 
> tokenize;__file__='/tmp/pip-build-Tcv7pk/functools32/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-4dDwiW-record/install-record.txt --single-version-externally-managed --compile:
>     Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/usr/local/lib/python2.7/dist-packages/setuptools/__init__.py", line 12, in <module>
>     import setuptools.version
>   File "/usr/local/lib/python2.7/dist-packages/setuptools/version.py", line 1, in <module>
>     import pkg_resources
>   File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 70, in <module>
>     import packaging.version
> ImportError: No module named packaging.version
> Cleaning up...
> Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-Tcv7pk/functools32/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-4dDwiW-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-Tcv7pk/functools32
> Storing debug log for failure in /root/.pip/pip.log
> The command '/bin/sh -c pip install -r requirements.txt' returned a non-zero code: 1

The problem seems to be solved if I upgrade pip inside Docker file after line 12 before installing requirements.
`RUN python -m pip install -U pip` 

Has anybody experienced similar behaviour?
Thanks!

**Comment by d-a-gorbachev** [comment]
You can use requirements-dev.txt
