### ISSUE TITLE
Support Kibana 5.x

### ISSUE THREAD

**Issue by outputexception** [bitsensor/elastalert#6]
Plz add support to kibana 5.x.

**Comment by Bizzelicious** [comment]
I guess you mean the Kibana plugin https://github.com/bitsensor/elastalert-kibana-plugin/issues ? 
This is a forked version of the plugin which can be used for kibana 5.X: https://github.com/baoban/elastalert-kibana-plugin. Just update kibana version to the version you are using in: [package.json](https://github.com/Baoban/elastalert-kibana-plugin/blob/kibana5/package.json)
