### ISSUE TITLE
writeback_index being ignored

### ISSUE THREAD

**Issue by fatalglitch** [bitsensor/elastalert#65]
Just built a new local testing environment, and I'm trying to use a different writeback_index. Modified elastalert.yaml, elastalert-test.yaml, and config.json to all match to the new writeback_index. However elastalert is still only creating elastalert_status on startup, not my defined writeback_index.

> > @bitsensor/elastalert@1.0.0 start /opt/elastalert-server
> > sh ./scripts/start.sh
> 
> 13:02:30.705Z  INFO elastalert-server: Config:  No config.dev.json file was found in /opt/elastalert-server/config/config.dev.json.
> 13:02:30.707Z  INFO elastalert-server: Config:  Proceeding to look for normal config file.
> 13:02:30.708Z  INFO elastalert-server: Config:  A config file was found in /opt/elastalert-server/config/config.json. Using that config.
> 13:02:30.714Z  INFO elastalert-server: Router:  Listening for GET request on /.
> 13:02:30.714Z  INFO elastalert-server: Router:  Listening for GET request on /status.
> 13:02:30.714Z  INFO elastalert-server: Router:  Listening for GET request on /status/control/:action.
> 13:02:30.714Z  INFO elastalert-server: Router:  Listening for GET request on /status/errors.
> 13:02:30.715Z  INFO elastalert-server: Router:  Listening for GET request on /rules.
> 13:02:30.716Z  INFO elastalert-server: Router:  Listening for GET request on /rules/:id.
> 13:02:30.716Z  INFO elastalert-server: Router:  Listening for POST request on /rules/:id.
> 13:02:30.716Z  INFO elastalert-server: Router:  Listening for DELETE request on /rules/:id.
> 13:02:30.716Z  INFO elastalert-server: Router:  Listening for GET request on /templates.
> 13:02:30.716Z  INFO elastalert-server: Router:  Listening for GET request on /templates/:id.
> 13:02:30.717Z  INFO elastalert-server: Router:  Listening for POST request on /templates/:id.
> 13:02:30.717Z  INFO elastalert-server: Router:  Listening for DELETE request on /templates/:id.
> 13:02:30.717Z  INFO elastalert-server: Router:  Listening for POST request on /test.
> 13:02:30.717Z  INFO elastalert-server: Router:  Listening for GET request on /config.
> 13:02:30.717Z  INFO elastalert-server: Router:  Listening for POST request on /config.
> 13:02:30.717Z  INFO elastalert-server: Router:  Listening for POST request on /download.
> 13:02:30.717Z  INFO elastalert-server: Router:  Listening for GET request on /metadata/:type.
> 13:02:30.717Z  INFO elastalert-server: Router:  Listening for GET request on /mapping/:index.
> 13:02:30.721Z  INFO elastalert-server: ProcessController:  Starting ElastAlert
> 13:02:30.721Z  INFO elastalert-server: ProcessController:  Creating index
> 13:02:31.451Z  INFO elastalert-server:
>     ProcessController:  Elastic Version:6
>     Mapping used for string:{'type': 'keyword'}
>     Index elastalert_status already exists. Skipping index creation.
> 
> 13:02:31.451Z  INFO elastalert-server: ProcessController:  Index create exited with code 0
> 13:02:31.451Z  INFO elastalert-server: ProcessController:  Starting elastalert with arguments [none]
> 13:02:31.457Z  INFO elastalert-server: ProcessController:  Started Elastalert (PID: 48)
> 13:02:31.458Z  INFO elastalert-server: Server:  Server listening on port 3030
> 13:02:31.459Z  INFO elastalert-server: Server:  Server started
> 13:02:32.024Z ERROR elastalert-server:
>     ProcessController:  WARNING:elasticsearch:GET http://elasticsearch:9200/somethingelse_elastalert_status/elastalert/_search?size=1000 [status:404 request:0.002s]

Contents of elastalert.yaml

> es_host: elasticsearch
> es_port: 9200
> rules_folder: rules
> run_every:
>   seconds: 60
> buffer_time:
>   minutes: 1
> writeback_index: somethingelse_elastalert_status
> alert_time_limit:
>   days: 2
> skip_invalid: True

Contents of config.json

> {
>   "appName": "elastalert-server",
>   "port": 3030,
>   "wsport": 3333,
>   "elastalertPath": "/opt/elastalert",
>   "verbose": false,
>   "es_debug": false,
>   "debug": false,
>   "rulesPath": {
>     "relative": true,
>     "path": "/rules"
>   },
>   "templatesPath": {
>     "relative": true,
>     "path": "/rule_templates"
>   },
>   "es_host": "elasticsearch",
>   "es_port": 9200,
>   "es_ssl": false,
>   "writeback_index": "somethingelse_elastalert_status"
> }

**Comment by martijnrondeel** [comment]
This issue has been fixed in the latest [2.0.0 release](https://github.com/bitsensor/elastalert/releases/tag/2.0.0) thanks to https://github.com/bitsensor/elastalert/pull/74.
