### ISSUE TITLE
Duplicated elastalert.py process

### ISSUE THREAD

**Issue by ricardo-maraschini** [bitsensor/elastalert#7]
Is it normal to have, inside the container, two `python elastalert/elastalert.py` processes running? I am receiving duplicated opsgenie alerts, i think it is a side effect of having two processes.

Maybe this is relevant:

https://github.com/bitsensor/elastalert/commit/a3c12c5ec1d0b07625f0329e4ceccb6da65c1bec

**Comment by nqkdev** [comment]
Master branch last update was a few months ago. You can try using develop branch instead.

**Comment by ricardo-maraschini** [comment]
Thanks. It works with the `develop` branch.
