### ISSUE TITLE
Using deprecated parameter in 6.6

### ISSUE THREAD

**Issue by frejonb** [bitsensor/elastalert#75]
Elasticsearch emits a million logs:
```
[WARN ][o.e.d.s.f.s.FetchSourceContext] [B15xXHa] Deprecated parameter [_source_include] used, expected [_source_includes] instead
```

in 6.6. How can I fix this?

**Comment by martijnrondeel** [comment]
I think this issue is related to [ElastAlert](https://github.com/Yelp/elastalert) itself, not the API.
