### ISSUE TITLE
REST port not active

### ISSUE THREAD

**Issue by moetemad** [bitsensor/elastalert#82]
My Dockerfile is as follows:

> ARG ELASTALERT_HOME=/opt/elastalert
> RUN apk add --update ca-certificates openssl-dev openssl libffi-dev gcc musl-dev wget && \
>     wget https://github.com/matsgoran/elastalert/archive/doc_type_and_support_for_es66_es7.zip -O elastalert.zip && \
>     unzip elastalert.zip && \
>     mv elastalert-* "${ELASTALERT_HOME}"
> WORKDIR "${ELASTALERT_HOME}"
> RUN sed -i 's/elasticsearch/elasticsearch>=7.0.0,<8.0.0/' requirements.txt && \
>     sed -i "s/'elasticsearch',/'elasticsearch>=7.0.0,<8.0.0',/" setup.py && \
>     python setup.py install && \
>     pip install -r requirements.txt
> FROM python:2.7-alpine AS runner
> RUN apk add --update --no-cache curl tzdata make libmagic
> COPY --from=builder /usr/local/lib/python2.7/site-packages/ /usr/local/lib/python2.7/site-packages/
> COPY --from=builder /opt/elastalert /opt/elastalert
> COPY --from=builder /usr/local/bin/elastalert* /usr/local/bin/
> WORKDIR /opt/elastalert
> COPY . /opt/elastalert
> EXPOSE 3030
> ENTRYPOINT ["/usr/local/bin/elastalert"]

And I have the following in my config.yaml:

`port: 3030
wsport: 3333
`

When I start the container, netstat returns ports connected to my elasticsearch 9200 port, and I see nothing listening on 3030. Doing a curl on that port also returns connection refused. Am I missing something?

**Comment by martijnrondeel** [comment]
You're not running ElastAlert from our repository but a fork with rudimentary 7.0 support. We'll add support for 7.0 when upstream Yelp has done so.

(The entrypoint is `/usr/local/bin/elastalert`, whereas it should run `npm start`)
