### ISSUE TITLE
ElastAlert V2.0.1 won't stay alive 

### ISSUE THREAD

**Issue by whiranpat** [bitsensor/elastalert#84]
Hello,
I spin up the docker elastalert server and the server would create the index on my elasticsearch server and then crash saying it wasn't able to communicate to the elasticsearch server which it then exited out.
I was testing throught it was a security group or firewalld issue but there wasn't any error there.
I revert it to v2.0.0 with same configuration and it is working now. I thought I should let you know that there is something weird with the connection changes between v2.0.0 and v2.0.1.
Hope this helps.

**Comment by mbassett** [comment]
Pretty sure this is because of the change in elasticsearch pip release 7.0.1
01:52:17.702Z ERROR elastalert-server:
    ProcessController:    File "/usr/lib/python2.7/site-packages/elasticsearch-7.0.1-py2.7.egg/elasticsearch/client/utils.py", line 84, in _wrapped
        return func(*args, params=params, **kwargs)
    TypeError: search() got an unexpected keyword argument 'doc_type'

**Comment by martijnrondeel** [comment]
@whiranpat Could you pull `bitsensor/elastalert:2.0.1` and test that, it should be fixed now.

**Comment by mmguero** [comment]
I am also facing this problem with `bitsensor/elastalert:2.0.1` (image id `f18338c0610a`) pulled this afternoon, here is my output:

```
 21:05:53.418Z  INFO elastalert-server:
     ProcessController:  Elastic Version:6
     Mapping used for string:{'type': 'keyword'}
     New index elastalert_status created
     Done!
     
 21:05:53.419Z  INFO elastalert-server: ProcessController:  Index create exited with code 0
 21:05:53.420Z  INFO elastalert-server: ProcessController:  Starting elastalert with arguments [none]
 21:05:53.428Z  INFO elastalert-server: ProcessController:  Started Elastalert (PID: 135)
 21:05:53.431Z  INFO elastalert-server: Server:  Server listening on port 3030
 21:05:53.433Z  INFO elastalert-server: Server:  Websocket listening on port 3333
 21:05:53.434Z  INFO elastalert-server: Server:  Server started
 (node:110) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'testFolder' of undefined
     at /opt/elastalert-server/src/controllers/test/index.js:18:64
 (node:110) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
 21:05:54.817Z ERROR elastalert-server:
     ProcessController:  Traceback (most recent call last):
       File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
     
 21:05:54.818Z ERROR elastalert-server:
     ProcessController:      "__main__", fname, loader, pkg_name)
       File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
         exec code in run_globals
       File "/opt/elastalert/elastalert/elastalert.py", line 1929, in <module>
         sys.exit(main(sys.argv[1:]))
       File "/opt/elastalert/elastalert/elastalert.py", line 1925, in main
         client.start()
       File "/opt/elastalert/elastalert/elastalert.py", line 1106, in start
     
 21:05:54.818Z ERROR elastalert-server:
     ProcessController:      self.run_all_rules()
       File "/opt/elastalert/elastalert/elastalert.py", line 1158, in run_all_rules
     
 21:05:54.818Z ERROR elastalert-server:
     ProcessController:      self.send_pending_alerts()
       File "/opt/elastalert/elastalert/elastalert.py", line 1534, in send_pending_alerts
     
 21:05:54.819Z ERROR elastalert-server:
     ProcessController:      pending_alerts = self.find_recent_pending_alerts(self.alert_time_limit)
       File "/opt/elastalert/elastalert/elastalert.py", line 1526, in find_recent_pending_alerts
     
 21:05:54.819Z ERROR elastalert-server:
     ProcessController:      size=1000)
       File "/usr/lib/python2.7/site-packages/elasticsearch-7.0.1-py2.7.egg/elasticsearch/client/utils.py", line 84, in _wrapped
     
 21:05:54.819Z ERROR elastalert-server:
     ProcessController:      return func(*args, params=params, **kwargs)
     TypeError: search() got an unexpected keyword argument 'doc_type'
     
 21:05:54.847Z ERROR elastalert-server: ProcessController:  ElastAlert exited with code 1
 21:05:54.847Z  INFO elastalert-server: Server:  Stopping server
 21:05:54.848Z  INFO elastalert-server: ProcessController:  ElastAlert is not running
 21:05:54.848Z  INFO elastalert-server: Server:  Server stopped. Bye!
```

**Comment by fattahantar** [comment]
+1 Do we have a solution for it? I tried latest and 2.0.1

06:07:18.802Z  INFO elastalert-server: ProcessController:  Creating index
06:07:19.569Z  INFO elastalert-server:
    ProcessController:  Elastic Version:6
    Mapping used for string:{'type': 'keyword'}
    Index elastalert already exists. Skipping index creation.

06:07:19.569Z  INFO elastalert-server: ProcessController:  Index create exited with code 0
06:07:19.569Z  INFO elastalert-server: ProcessController:  Setting ElastAlert query beginning to time 2014-01-01T00:00:00
06:07:19.569Z  INFO elastalert-server: ProcessController:  Setting ElastAlert query ending to time 2016-01-01T00:00:00
06:07:19.570Z  INFO elastalert-server: ProcessController:  Setting ElastAlert verbose mode. This will increase the logging verboseness, which allows you to see information about the state of queries.
06:07:19.570Z  INFO elastalert-server: ProcessController:  Setting ElastAlert es_debug mode. This will enable logging for all queries made to Elasticsearch.
06:07:19.570Z  INFO elastalert-server: ProcessController:  Starting elastalert with arguments --start 2014-01-01T00:00:00 --end 2016-01-01T00:00:00 --verbose --es_debug
06:07:19.578Z  INFO elastalert-server: ProcessController:  Started Elastalert (PID: 48)
06:07:19.580Z  INFO elastalert-server: Server:  Server listening on port 3030
06:07:19.580Z  INFO elastalert-server: Server:  Websocket listening on port 3333
06:07:19.581Z  INFO elastalert-server: Server:  Server started
06:07:20.249Z ERROR elastalert-server:
    ProcessController:  INFO:elastalert:Starting up

06:07:20.254Z ERROR elastalert-server:
    ProcessController:  Traceback (most recent call last):
      File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main

06:07:20.255Z ERROR elastalert-server:
    ProcessController:      "__main__", fname, loader, pkg_name)
      File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
      File "/opt/elastalert/elastalert/elastalert.py", line 1929, in <module>

06:07:20.256Z ERROR elastalert-server:
    ProcessController:      sys.exit(main(sys.argv[1:]))
      File "/opt/elastalert/elastalert/elastalert.py", line 1925, in main

06:07:20.256Z ERROR elastalert-server:
    ProcessController:      client.start()
      File "/opt/elastalert/elastalert/elastalert.py", line 1106, in start

06:07:20.257Z ERROR elastalert-server:
    ProcessController:      self.run_all_rules()
      File "/opt/elastalert/elastalert/elastalert.py", line 1158, in run_all_rules

06:07:20.257Z ERROR elastalert-server:
    ProcessController:      self.send_pending_alerts()
      File "/opt/elastalert/elastalert/elastalert.py", line 1534, in send_pending_alerts

06:07:20.257Z ERROR elastalert-server:
    ProcessController:      pending_alerts = self.find_recent_pending_alerts(self.alert_time_limit)
      File "/opt/elastalert/elastalert/elastalert.py", line 1526, in find_recent_pending_alerts
        size=1000)
      File "/usr/lib/python2.7/site-packages/elasticsearch-7.0.1-py2.7.egg/elasticsearch/client/utils.py", line 84, in _wrapped
        return func(*args, params=params, **kwargs)
    TypeError: search() got an unexpected keyword argument 'doc_type'

06:07:20.284Z ERROR elastalert-server: ProcessController:  ElastAlert exited with code 1
06:07:20.284Z  INFO elastalert-server: Server:  Stopping server
06:07:20.285Z  INFO elastalert-server: ProcessController:  ElastAlert is not running
06:07:20.285Z  INFO elastalert-server: Server:  Server stopped. Bye!

**Comment by whiranpat** [comment]
yeah I am getting this issue too. The 2.0.1 docker image in docker hub is 8 days old. Not sure, if they updated the official image yet

**Comment by mbassett** [comment]
I just went with 2.0.0

**Comment by martijnrondeel** [comment]
So our CI rebuilt the 2.0.1 image which made ElastAlert grab the latest ElasticSearch dependency (which means 2.0.1 only works for ES 7+). Using 2.0.0 works for now, I'll improve our CI so there can be multiple ES versions supported per release.

If you *are* using ES 7+ please use the beta release (https://github.com/bitsensor/elastalert/releases/tag/3.0.0-beta.0)
