### ISSUE TITLE
docker image "bitsensor/elastalert:2.0.1" contains "@bitsensor/elastalert@3.0.0-beta.0"

### ISSUE THREAD

**Issue by hrbu** [bitsensor/elastalert#86]
The image `bitsensor/elastalert:2.0.1` was accidentally (?) updated (@see https://hub.docker.com/r/bitsensor/elastalert/tags). 

It now contains `@bitsensor/elastalert@3.0.0-beta.0` (instead of `@bitsensor/elastalert@2.0.1`).

**Comment by martijnrondeel** [comment]
This should be fixed now, sorry for the inconvenience.
