### ISSUE TITLE
Get Error when installing dependencies

### ISSUE THREAD

**Issue by jreker** [bitsensor/elastalert#9]
I try to install the dependencies with npm install in the elastalert directory.
I get the following error message:

`npm` ERR! husky@0.11.9 install: `node ./bin/install.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the husky@0.11.9 install script 'node ./bin/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the husky package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs husky
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls husky
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/elastalert/npm-debug.log

**Comment by RubieV** [comment]
I propose you use the Docker container or find help with the Husky maintainers.
