### ISSUE TITLE
Run Elastalert Docker Image with Elasticsearch 7.1.0: Error ProcessController

### ISSUE THREAD

**Issue by CyberAbwehr** [bitsensor/elastalert#95]
Elasticsearch : 7.1.0

Log:

> @bitsensor/elastalert@2.0.1 start /opt/elastalert-server
> sh ./scripts/start.sh

08:09:10.039Z  INFO elastalert-server: Config:  No config.dev.json file was found in /opt/elastalert-server/config/config.dev.json.
08:09:10.040Z  INFO elastalert-server: Config:  Proceeding to look for normal config file.
08:09:10.040Z  INFO elastalert-server: Config:  A config file was found in /opt/elastalert-server/config/config.json. Using that config.
08:09:10.048Z  INFO elastalert-server: Router:  Listening for GET request on /.
08:09:10.049Z  INFO elastalert-server: Router:  Listening for GET request on /status.
08:09:10.049Z  INFO elastalert-server: Router:  Listening for GET request on /status/control/:action.
08:09:10.049Z  INFO elastalert-server: Router:  Listening for GET request on /status/errors.
08:09:10.049Z  INFO elastalert-server: Router:  Listening for GET request on /rules.
08:09:10.050Z  INFO elastalert-server: Router:  Listening for GET request on /rules/:id.
08:09:10.052Z  INFO elastalert-server: Router:  Listening for POST request on /rules/:id.
08:09:10.052Z  INFO elastalert-server: Router:  Listening for DELETE request on /rules/:id.
08:09:10.052Z  INFO elastalert-server: Router:  Listening for GET request on /templates.
08:09:10.053Z  INFO elastalert-server: Router:  Listening for GET request on /templates/:id.
08:09:10.053Z  INFO elastalert-server: Router:  Listening for POST request on /templates/:id.
08:09:10.053Z  INFO elastalert-server: Router:  Listening for DELETE request on /templates/:id.
08:09:10.053Z  INFO elastalert-server: Router:  Listening for POST request on /test.
08:09:10.053Z  INFO elastalert-server: Router:  Listening for GET request on /config.
08:09:10.053Z  INFO elastalert-server: Router:  Listening for POST request on /config.
08:09:10.053Z  INFO elastalert-server: Router:  Listening for POST request on /download.
08:09:10.053Z  INFO elastalert-server: Router:  Listening for GET request on /metadata/:type.
08:09:10.053Z  INFO elastalert-server: Router:  Listening for GET request on /mapping/:index.
08:09:10.053Z  INFO elastalert-server: Router:  Listening for POST request on /search/:index.
08:09:10.055Z  INFO elastalert-server: ProcessController:  Starting ElastAlert
08:09:10.055Z  INFO elastalert-server: ProcessController:  Creating index
08:09:10.337Z  INFO elastalert-server:
    ProcessController:  Elastic Version:7
    Mapping used for string:{'type': 'keyword'}
    Index elastalert_status already exists. Skipping index creation. 

08:09:10.337Z  INFO elastalert-server: ProcessController:  Index create exited with code 0
08:09:10.338Z  INFO elastalert-server: ProcessController:  Starting elastalert with arguments [none]
08:09:10.343Z  INFO elastalert-server: ProcessController:  Started Elastalert (PID: 36)
08:09:10.344Z  INFO elastalert-server: Server:  Server listening on port 3030
08:09:10.344Z  INFO elastalert-server: Server:  Websocket listening on port 3333
08:09:10.345Z  INFO elastalert-server: Server:  Server started
08:09:10.776Z ERROR elastalert-server:
    ProcessController:  Traceback (most recent call last):
      File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
        "__main__", fname, loader, pkg_name)
      File "/usr/lib/python2.7/runpy.py", line 72, in _run_code

08:09:10.777Z ERROR elastalert-server:
    ProcessController:      exec code in run_globals
      File "/opt/elastalert/elastalert/elastalert.py", line 1929, in <module>
        sys.exit(main(sys.argv[1:]))
      File "/opt/elastalert/elastalert/elastalert.py", line 1925, in main
    
08:09:10.777Z ERROR elastalert-server:
    ProcessController:      client.start()
      File "/opt/elastalert/elastalert/elastalert.py", line 1106, in start    

08:09:10.785Z ERROR elastalert-server:
    ProcessController:      self.run_all_rules()
      File "/opt/elastalert/elastalert/elastalert.py", line 1158, in run_all_rules
        self.send_pending_alerts()
      File "/opt/elastalert/elastalert/elastalert.py", line 1534, in send_pending_alerts
        pending_alerts = self.find_recent_pending_alerts(self.alert_time_limit)
      File "/opt/elastalert/elastalert/elastalert.py", line 1526, in find_recent_pending_alerts
        size=1000)
      File "/usr/lib/python2.7/site-packages/elasticsearch-7.0.1-py2.7.egg/elasticsearch/client/utils.py", line 84, in _wrapped
        return func(*args, params=params, **kwargs)
    TypeError: search() got an unexpected keyword argument 'doc_type'
    
08:09:10.803Z ERROR elastalert-server: ProcessController:  ElastAlert exited with code 1
08:09:10.803Z  INFO elastalert-server: Server:  Stopping server
08:09:10.803Z  INFO elastalert-server: ProcessController:  ElastAlert is not running
08:09:10.803Z  INFO elastalert-server: Server:  Server stopped. Bye!

**Comment by webhead404** [comment]
I am seeing this too. Is the only solution to build it from scratch for now?

**Comment by CyberAbwehr** [comment]
I have not test it now from scratch, need to do that.
If there is no solution, I will take a view to the new Amazon solution Open Distro.

**Comment by bbarclay** [comment]
Same problem here. Exact same problem.

**Comment by branchnetconsulting** [comment]
Yes, same problem here with the ElastAlert master branch used against Elasticsearch 7.1.1.   What to do?  Are there instructions somewhere for building this special ElastAlert fork from scratch, assuming that would help for use with Elasticsearch 7+?

**Comment by bbarclay** [comment]
It was a capital letter in one of the yaml files that was causing the issue. It was something like 
tagOn: 
That's not it.  wish I would have posted right away. But that capital letter was preventing me from starting it.

**Comment by bbarclay** [comment]
Using the standalone installation, I had the same problem. That gave me the verbose output which allowed me to better diagnose it.

**Comment by branchnetconsulting** [comment]
Any idea which yaml file you had to tweak?  I just looked through all the yaml files referred to in the example "docker run" command and I didn't see any likely candidates to fix.

How does one do a standalone installation of this fork of ElastAlert?  So far I've only been able to find instructions for installing it as a Docker container.  

Kevin

**Comment by bbarclay** [comment]
Actually I was using the standalone but it wont' work with the plugin. So now I'm back to square one if we want to use the plugin. but this pip install "elastalert>=0.2.0b"

Worked for me because I was getting simular errors still in the standalone. So I'm not sure what might be missing in this build that would be causing these issues. but I'm imagining it's something that is missing from v .1 to v2.

**Comment by bbarclay** [comment]
I think it's because, although somehow, indexes connect. There is another call to elasticsearch, possibly form an unrelate file. That is not mounting properly or something. Then it will try to connect to localhost:9200 because it's not picking up on mounted configurations.

**Comment by bbarclay** [comment]
//. YOu need to properly configure your credentials in your config.json file. Including password, crt files or enable ssl, it seems.

**Comment by atombcss** [comment]
I am stuck with this same error.  Is there any other work around with the docker install?

**Comment by martijnrondeel** [comment]
Please use the beta release with ES 7 support:

https://github.com/bitsensor/elastalert/releases/tag/3.0.0-beta.0

**Comment by Hitesh-Agrawal** [comment]
`FROM python:3.6-alpine as py-ea
ARG ELASTALERT_VERSION=v0.2.1
ENV ELASTALERT_VERSION=${ELASTALERT_VERSION}
# URL from which to download Elastalert.
ARG ELASTALERT_URL=https://github.com/Yelp/elastalert/archive/$ELASTALERT_VERSION.zip
ENV ELASTALERT_URL=${ELASTALERT_URL}
# Elastalert home directory full path.
ENV ELASTALERT_HOME /opt/elastalert

WORKDIR /opt

RUN python -m pip install --upgrade pip

#RUN apk add --update --no-cache ca-certificates openssl-dev openssl python2-dev python2 py2-pip py2-yaml libffi-dev gcc musl-dev wget && \

RUN apk add --update --no-cache ca-certificates openssl-dev openssl libffi-dev gcc musl-dev wget && \
# Download and unpack Elastalert.
    wget -O elastalert.zip "${ELASTALERT_URL}" && \
    unzip elastalert.zip && \
    rm elastalert.zip && \
    mv e* "${ELASTALERT_HOME}"

WORKDIR "${ELASTALERT_HOME}"

# Install Elastalert.
# see: https://github.com/Yelp/elastalert/issues/1654
RUN sed -i 's/jira>=1.0.10/jira>=1.0.10,<1.0.15/g' setup.py && \
    python setup.py install && \
    pip install -r requirements.txt

FROM node:alpine
LABEL maintainer="BitSensor <dev@bitsensor.io>"
# Set timezone for this container
ENV TZ Etc/UTC

RUN apk add --no-cache python python-dev python3 python3-dev curl tzdata make libmagic g++ gcc libgcc libstdc++\
    linux-headers build-base bash git ca-certificates && \
    python3 -m ensurepip && \
    rm -r /usr/lib/python*/ensurepip && \
    pip3 install --upgrade pip setuptools && \
    if [ ! -e /usr/bin/pip ]; then ln -s pip3 /usr/bin/pip ; fi && \
    ln -sf python3 /usr/bin/python && \
    rm -r /root/.cache

COPY --from=py-ea /usr/local/lib/python3.6/site-packages /usr/lib/python3.6/site-packages
COPY --from=py-ea /opt/elastalert /opt/elastalert
COPY --from=py-ea /usr/local/bin/elastalert* /usr/bin/

WORKDIR /opt/elastalert-server
COPY . /opt/elastalert-server
RUN npm install babel-preset-env && \
    npm install --production --quiet
COPY config/elastalert.yaml /opt/elastalert/config.yaml
COPY config/elastalert-test.yaml /opt/elastalert/config-test.yaml
COPY config/config.json config/config.json
COPY rule_templates/ /opt/elastalert/rule_templates
COPY elastalert_modules/ /opt/elastalert/elastalert_modules

# Add default rules directory
# Set permission as unpriviledged user (1000:1000), compatible with Kubernetes
RUN mkdir -p /opt/elastalert/rules/ /opt/elastalert/server_data/tests/ \
    && chown -R node:node /opt

USER node

EXPOSE 3030
ENTRYPOINT ["npm", "start"]`

Save the above file as Dockerfile and build the image
`docker build -t <dockertag> -f Dockerfile .`
Though it does give some errors while build works perfectly with my elasticsearch 7.1.3 cluster.

Also within your  kubernetes deployment yaml , don't forget to add below, otherwise you will not be able to save the rules to the rules directory.
      `securityContext:
        fsGroup: 1000`

**Comment by Hitesh-Agrawal** [comment]
[Dockerfile.log](https://github.com/bitsensor/elastalert/files/3621099/Dockerfile.log)

Build the docker image using the above Dockerfile for ES 7.x index, works pretty well for me.
See below
[container.log](https://github.com/bitsensor/elastalert/files/3621116/container.log)

And here is the testing rule via web interface
<img width="754" alt="Elastalert-Web-Testing" src="https://user-images.githubusercontent.com/39374310/65039851-cd926a00-d970-11e9-9eac-9ae56cad71c1.png">

**Comment by Rambabuyendru520** [comment]
> Elasticsearch : 7.1.0
> 
> Log:
> 
> > @bitsensor/elastalert@2.0.1 start /opt/elastalert-server
> > sh ./scripts/start.sh
> 
> 08:09:10.039Z INFO elastalert-server: Config: No config.dev.json file was found in /opt/elastalert-server/config/config.dev.json.
> 08:09:10.040Z INFO elastalert-server: Config: Proceeding to look for normal config file.
> 08:09:10.040Z INFO elastalert-server: Config: A config file was found in /opt/elastalert-server/config/config.json. Using that config.
> 08:09:10.048Z INFO elastalert-server: Router: Listening for GET request on /.
> 08:09:10.049Z INFO elastalert-server: Router: Listening for GET request on /status.
> 08:09:10.049Z INFO elastalert-server: Router: Listening for GET request on /status/control/:action.
> 08:09:10.049Z INFO elastalert-server: Router: Listening for GET request on /status/errors.
> 08:09:10.049Z INFO elastalert-server: Router: Listening for GET request on /rules.
> 08:09:10.050Z INFO elastalert-server: Router: Listening for GET request on /rules/:id.
> 08:09:10.052Z INFO elastalert-server: Router: Listening for POST request on /rules/:id.
> 08:09:10.052Z INFO elastalert-server: Router: Listening for DELETE request on /rules/:id.
> 08:09:10.052Z INFO elastalert-server: Router: Listening for GET request on /templates.
> 08:09:10.053Z INFO elastalert-server: Router: Listening for GET request on /templates/:id.
> 08:09:10.053Z INFO elastalert-server: Router: Listening for POST request on /templates/:id.
> 08:09:10.053Z INFO elastalert-server: Router: Listening for DELETE request on /templates/:id.
> 08:09:10.053Z INFO elastalert-server: Router: Listening for POST request on /test.
> 08:09:10.053Z INFO elastalert-server: Router: Listening for GET request on /config.
> 08:09:10.053Z INFO elastalert-server: Router: Listening for POST request on /config.
> 08:09:10.053Z INFO elastalert-server: Router: Listening for POST request on /download.
> 08:09:10.053Z INFO elastalert-server: Router: Listening for GET request on /metadata/:type.
> 08:09:10.053Z INFO elastalert-server: Router: Listening for GET request on /mapping/:index.
> 08:09:10.053Z INFO elastalert-server: Router: Listening for POST request on /search/:index.
> 08:09:10.055Z INFO elastalert-server: ProcessController: Starting ElastAlert
> 08:09:10.055Z INFO elastalert-server: ProcessController: Creating index
> 08:09:10.337Z INFO elastalert-server:
> ProcessController: Elastic Version:7
> Mapping used for string:{'type': 'keyword'}
> Index elastalert_status already exists. Skipping index creation.
> 
> 08:09:10.337Z INFO elastalert-server: ProcessController: Index create exited with code 0
> 08:09:10.338Z INFO elastalert-server: ProcessController: Starting elastalert with arguments [none]
> 08:09:10.343Z INFO elastalert-server: ProcessController: Started Elastalert (PID: 36)
> 08:09:10.344Z INFO elastalert-server: Server: Server listening on port 3030
> 08:09:10.344Z INFO elastalert-server: Server: Websocket listening on port 3333
> 08:09:10.345Z INFO elastalert-server: Server: Server started
> 08:09:10.776Z ERROR elastalert-server:
> ProcessController: Traceback (most recent call last):
> File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
> "**main**", fname, loader, pkg_name)
> File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
> 
> 08:09:10.777Z ERROR elastalert-server:
> ProcessController: exec code in run_globals
> File "/opt/elastalert/elastalert/elastalert.py", line 1929, in
> sys.exit(main(sys.argv[1:]))
> File "/opt/elastalert/elastalert/elastalert.py", line 1925, in main
> 
> 08:09:10.777Z ERROR elastalert-server:
> ProcessController: client.start()
> File "/opt/elastalert/elastalert/elastalert.py", line 1106, in start
> 
> 08:09:10.785Z ERROR elastalert-server:
> ProcessController: self.run_all_rules()
> File "/opt/elastalert/elastalert/elastalert.py", line 1158, in run_all_rules
> self.send_pending_alerts()
> File "/opt/elastalert/elastalert/elastalert.py", line 1534, in send_pending_alerts
> pending_alerts = self.find_recent_pending_alerts(self.alert_time_limit)
> File "/opt/elastalert/elastalert/elastalert.py", line 1526, in find_recent_pending_alerts
> size=1000)
> File "/usr/lib/python2.7/site-packages/elasticsearch-7.0.1-py2.7.egg/elasticsearch/client/utils.py", line 84, in _wrapped
> return func(*args, params=params, **kwargs)
> TypeError: search() got an unexpected keyword argument 'doc_type'
> 
> 08:09:10.803Z ERROR elastalert-server: ProcessController: ElastAlert exited with code 1
> 08:09:10.803Z INFO elastalert-server: Server: Stopping server
> 08:09:10.803Z INFO elastalert-server: ProcessController: ElastAlert is not running
> 08:09:10.803Z INFO elastalert-server: Server: Server stopped. Bye!

Hii ,am also facing same issue,please help me any one.thank you.

**Comment by shettypriy** [comment]
> [Dockerfile.log](https://github.com/bitsensor/elastalert/files/3621099/Dockerfile.log)
> 
> Build the docker image using the above Dockerfile for ES 7.x index, works pretty well for me.
> See below
> [container.log](https://github.com/bitsensor/elastalert/files/3621116/container.log)
> 
> And here is the testing rule via web interface
> <img alt="Elastalert-Web-Testing" width="754" src="https://user-images.githubusercontent.com/39374310/65039851-cd926a00-d970-11e9-9eac-9ae56cad71c1.png">

Could you please provide the complete steps to install elastalert server using the docker

**Comment by CyberAbwehr** [comment]
We have it (ELK 7.4.x) now running over month in our production and demo system and it works.
We have also test it now with ELK 7.6.x including secure communication, it runs stable.
It runs all in docker containers.

office@c4sam.com
